###
GET http://localhost:8080/tasks/statuses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY

###
GET http://localhost:8080/tasks/repetitions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY

###
GET http://localhost:8080/tasks/priorities
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY

###
GET http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4OTE1Nzk2LCJleHAiOjE2ODkwMDIxOTZ9.-6Y2lbjfZHb3BemBopE_9OLPloljcyV1H8E_JbVnTr0

###
GET http://localhost:8080/tasks/categories?categoryId=9 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY

###
GET http://localhost:8080/tasks/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY

###
POST http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbW9uZ3VzIiwiaWF0IjoxNjg4ODk5MDU4LCJleHAiOjE2ODg5ODU0NTh9.F1do8kXivZ8URgxNOuic9zJKRixsGcxbyPAchGXGZf4
Content-Type: application/json

{
  "title": "Позвонить Серёге",
  "description": "включить телефон, открыть контакты и нажать звонок",
  "taskDate": "2023-07-08 12:12:10",
  "status": {
        "id": 1 
    },
    "category": {
        "id": 9
    },
    "repetition": {
        "id": 1 
    },
    "priority": {
        "id": 1 
    }
}

###
PUT http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY
Content-Type: application/json

{
  "id": 12,
  "title": "Позвонить Игорю",
  "description": "включить телефон, открыть контакты и нажать звонок",
  "taskDate": "2023-07-08 20:35:10",
  "status": {
        "id": 1 
    },
    "category": {
        "id": 9
    },
    "repetition": {
        "id": 1 
    },
    "priority": {
        "id": 1 
    }
}

###
DELETE http://localhost:8080/tasks/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXBlZ3VzIiwiaWF0IjoxNjg4ODk1NjQ1LCJleHAiOjE2ODg5ODIwNDV9.s2cIXE0Lv-0xqw_EVG1SXBUxKAq-g0cLCDynS1lPYEY
